In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

In [7]:
a.ndim

2

In [8]:
a.dtype

dtype('int64')

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [13]:
b = np.arange(6)

In [14]:
print(b)

[0 1 2 3 4 5]


In [16]:
for row in b:
    print(row)


0
1
2
3
4
5


In [18]:
a.resize((3,5))

In [19]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
rg = np.random.default_rng()

In [24]:
c = np.floor(10 * rg.random((2, 2)))

In [25]:
print(c)

[[4. 8.]
 [7. 3.]]


In [26]:
arr = np.arange(1000)
print(arr.size*arr.itemsize)

8000


In [31]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1,"\n")
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2,"\n")



1D Array: [1 2 3 4 5] 

2D Array:
 [[1 2 3]
 [4 5 6]] 



In [32]:
arr_linspace = np.linspace(1, 10, 5)
print("NumPy linspace:", arr_linspace)

NumPy linspace: [ 1.    3.25  5.5   7.75 10.  ]


In [34]:
arr_range = np.arange(9)
arr_reshaped = arr_range.reshape(3, 3)
print("Reshaped Array:\n", arr_reshaped)

Reshaped Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
arr_flattened = arr_reshaped.ravel()
print("Flattened Array:", arr_flattened)

Flattened Array: [0 1 2 3 4 5 6 7 8]


In [36]:
arr_sqrt = np.sqrt(arr_range)
print("Square root of elements:\n", arr_sqrt)

Square root of elements:
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712]


In [37]:
# Creating two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Performing matrix multiplication (dot product)
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Product:\n", matrix_product,"\n\n")

Matrix Product:
 [[19 22]
 [43 50]] 




In [38]:
arr = np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in arr:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [39]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
